### ISSUE TITLE
remove top spacing without custom snippet

### ISSUE THREAD

**Issue by elisey243** [sanoojes/Spicetify-ShadeX#4]
rn im using custom snippet from marketplace for removing top spacing. With new Spotify interface i think it's better to remove that spacing by default

**no snippet**
![image](https://github.com/user-attachments/assets/e6519f38-45a1-40f2-a15f-7f0cab914f1f)

**with snippet**
![image](https://github.com/user-attachments/assets/50c8e8dc-60cb-4883-a554-781a2507143a)

The main problem, which why im here - is because snippets sometimes have an issue with loading. As a result - they doesn't work from start the app. The solve - reinstalling snippet, thats annoying to do every time.

**Comment by th3r1ko** [comment]
I'm here for the same reason too. It's annoying to reinstall snippet every time

**Comment by sanoojes** [comment]
Sorry, everyone, I haven't checked out the ShadeX theme in a long time. I'll be fixing these issues as soon as possible.

**Comment by th3r1ko** [comment]
@sanoojes and I would be VERY grateful if you made a theme version without transparency. Like Dark and Dark w/out transparency

**Comment by sanoojes** [comment]
What do you mean by transparency ? the blur on headers ?

**Comment by th3r1ko** [comment]
Yes! The blur on headers
![изображение](https://github.com/user-attachments/assets/7737032d-7941-434b-9eac-98187191dd03)

**Comment by sanoojes** [comment]
reinstall the theme as new scripts are added @elisey243 @th3r1ko

**Comment by sanoojes** [comment]
> Yes! The blur on headers ![изображение](https://private-user-images.githubusercontent.com/100483932/384691298-7737032d-7941-434b-9eac-98187191dd03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyODkyMDUsIm5iZiI6MTczMTI4ODkwNSwicGF0aCI6Ii8xMDA0ODM5MzIvMzg0NjkxMjk4LTc3MzcwMzJkLTc5NDEtNDM0Yi05ZWFjLTk4MTg3MTkxZGQwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwMTM1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjVlZDJmODc5ZGFjMDEyNTdlMTA4MDEwOTFiZWJkYzdmZDZkMzAzYTlkN2M4NTU2NTFkNzkzNzI5NjFkMjRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FjLtfVhdsNOPU7nOLpVMqjrU7MA4DNDv-J5dldshXCo)

add this snippet to do that
```css
aside[aria-label="Now playing view"] .fAte2d0xETy7pnDUAgHY, aside[aria-label="Now playing view"] .mdMUqcSHFw1lZIcYEblu,.main-home-filterChipsSection, .main-topBar-background, .main-trackList-trackListHeaderStuck.main-trackList-trackListHeader{
  --top-bar-backdrop: none !important;
  background: var(--spice-main) !important;
}
```
